# Generated by Django 4.2 on 2023-04-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_steps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Steps',
            new_name='RecipeStep',
        ),
    ]
